### ISSUE TITLE
Update libsodium to 0.7

### ISSUE THREAD

**Issue by neuegram** [jasonmccampbell/GoSodium#4]
Additions to libsodium that are available in a later version, the following in particular, would be helpful for some of my other projects:
- crypto_sign_ed25519_pk_to_curve25519()
- crypto_sign_ed25519_sk_to_curve25519()
- crypto_sign_ed25519_sk_to_seed()
- crypto_sign_ed25519_sk_to_pk()

**Comment by neuegram** [comment]
Note that 0.7 has yet to have an official release, so this issue is in anticpation of it and can still include 0.6.1 within its scope

**Comment by jedisct1** [comment]
0.7 is likely to be released tomorrow.

**Comment by neuegram** [comment]
@jedisct1 Perfect! I'll probably end up wrapping it tomorrow then!

**Comment by neuegram** [comment]
Libsodium 7.0 signing functions have been added to my fork. There is an existing pull request here as well.
